# Multi-objective Risk-based Resource Allocation

In [2]:
import geopandas as gp
import networkx as nx
import pandas as pd
import numpy as np
import unidecode
import string
import datetime
import seaborn as sn
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
import scipy.stats
import warnings
from scipy.stats import gaussian_kde
from matplotlib.patches import Patch
warnings.filterwarnings('ignore')
from sklearn import preprocessing
from matplotlib.patches import Patch
import matplotlib.colors 

from scipy.stats import chisquare, anderson, kstest

import matplotlib.pylab as plt
from matplotlib.lines import Line2D
import matplotlib.colors as colors
from matplotlib.cm import ScalarMappable
import matplotlib.colors as mcolors
from scipy.spatial import distance

def truncate_colormap(cmap, minval=0.0, maxval=1.0, n=100):
    new_cmap = colors.LinearSegmentedColormap.from_list(
        'trunc({n},{a:.2f},{b:.2f})'.format(n=cmap.name, a=minval, b=maxval),
        cmap(np.linspace(minval, maxval, n)))
    return new_cmap

# Load the Urban Sector Shapes

In [4]:
sectorUrbano = gp.read_file('./Data/MGN2018_URB_SECTOR')
sectorUrbano = sectorUrbano[(sectorUrbano['DPTO_CCDGO'] == '11') & (sectorUrbano['SETU_CCDGO'] != '0001')]
tost = sectorUrbano.copy()
tost = tost.to_crs({'init': 'epsg:3857'})
tost['area'] = tost['geometry'].area/ 10**6
dictAreas = tost.set_index('SETU_CCDGO')['area'].to_dict()
sectorUrbano['area'] = sectorUrbano['SETU_CCDGO'].apply(lambda x: dictAreas[x])
sectorUrbano['centroid'] = sectorUrbano.centroid

sectorUrbano

,DPTO_CCDGO,MPIO_CCDGO,CPOB_CCDGO,SETU_CCNCT,SHAPE_Leng,SHAPE_Area,SETU_CCDGO,geometry,area,centroid
1538,11,11001,11001000,110011000000001101,0.017602,0.000014,1101,"POLYGON ((-74.08034 4.58187, -74.08064 4.58165...",0.172533,POINT (-74.08160 4.58323)
1539,11,11001,11001000,110011000000001102,0.024178,0.000021,1102,"POLYGON ((-74.07819 4.58107, -74.07789 4.58081...",0.266636,POINT (-74.08002 4.57926)
1540,11,11001,11001000,110011000000001103,0.051139,0.000072,1103,"POLYGON ((-74.07046 4.57786, -74.07037 4.57765...",0.896132,POINT (-74.07353 4.57410)
1541,11,11001,11001000,110011000000001104,0.032833,0.000032,1104,"POLYGON ((-74.06825 4.56809, -74.06821 4.56800...",0.400737,POINT (-74.06817 4.56410)
1542,11,11001,11001000,110011000000001105,0.072244,0.000071,1105,"POLYGON ((-74.07426 4.56748, -74.07413 4.56735...",0.885145,POINT (-74.07707 4.56209)
...,...,...,...,...,...,...,...,...,...,...
2164,11,11001,11001000,110011000000009218,0.048764,0.000086,9218,"POLYGON ((-74.12461 4.75408, -74.12354 4.75406...",1.071749,POINT (-74.11539 4.75006)
2165,11,11001,11001000,110011000000009219,0.058952,0.000052,9219,"POLYGON ((-74.11956 4.74809, -74.11954 4.74809...",0.641471,POINT (-74.12417 4.74352)
2166,11,11001,11001000,110011000000009220,0.036532,0.000043,9220,"POLYGON ((-74.09222 4.73695, -74.09221 4.73695...",0.528884,POINT (-74.09257 4.73487)
2167,11,11001,11001000,110011000000009221,0.033188,0.000028,9221,"POLYGON ((-74.12395 4.74975, -74.12378 4.74919...",0.349619,POINT (-74.12691 4.74612)
2168,11,11001,11001000,110011000000009222,0.083100,0.000214,9222,"POLYGON ((-74.11508 4.76192, -74.11392 4.76096...",2.656149,POINT (-74.10850 4.75636)

## Read the vulnerability variables

In [5]:
variables = pd.read_excel("./Data/variables_vulnerability.xlsx")

variables = variables[['SETU_CCDGO'] + variables.keys()[-15:].tolist()]
factors = variables.keys()[-15:].tolist()
variablesdict = variables.set_index('SETU_CCDGO', drop=True).to_dict()

sectorUrbanoWithVariables = sectorUrbano.copy()

for fc in factors:
    sectorUrbanoWithVariables[fc] = sectorUrbano['SETU_CCDGO'].apply(lambda x: variablesdict[fc][int(x)])

sectorUrbanoWithVariables = sectorUrbanoWithVariables.rename(columns={"Geographic Spread": "Geographic Impact"})
sectorUrbanoWithVariables

,DPTO_CCDGO,MPIO_CCDGO,CPOB_CCDGO,SETU_CCNCT,SHAPE_Leng,SHAPE_Area,SETU_CCDGO,geometry,area,centroid,...,Educational,Cultural,Sports,Food market,Formal labor,Informal labor,Public Transportation Dependency,Transmission Routes,Geographic Impact,Transmisibility
1538,11,11001,11001000,110011000000001101,0.017602,0.000014,1101,"POLYGON ((-74.08034 4.58187, -74.08064 4.58165...",0.172533,POINT (-74.08160 4.58323),...,37,5,3,0,2369,0.69,97696.41712,30939,24653,54096
1539,11,11001,11001000,110011000000001102,0.024178,0.000021,1102,"POLYGON ((-74.07819 4.58107, -74.07789 4.58081...",0.266636,POINT (-74.08002 4.57926),...,37,5,3,0,2369,0.69,97696.41712,30939,24653,54096
1540,11,11001,11001000,110011000000001103,0.051139,0.000072,1103,"POLYGON ((-74.07046 4.57786, -74.07037 4.57765...",0.896132,POINT (-74.07353 4.57410),...,12,17,0,1,910,0.24,95716.00310,36005,18931,54182
1541,11,11001,11001000,110011000000001104,0.032833,0.000032,1104,"POLYGON ((-74.06825 4.56809, -74.06821 4.56800...",0.400737,POINT (-74.06817 4.56410),...,34,17,0,1,1728,0.54,119887.70640,55448,39366,111982
1542,11,11001,11001000,110011000000001105,0.072244,0.000071,1105,"POLYGON ((-74.07426 4.56748, -74.07413 4.56735...",0.885145,POINT (-74.07707 4.56209),...,34,17,0,1,1728,0.54,119887.70640,55448,39366,111982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2164,11,11001,11001000,110011000000009218,0.048764,0.000086,9218,"POLYGON ((-74.12461 4.75408, -74.12354 4.75406...",1.071749,POINT (-74.11539 4.75006),...,51,14,1,1,6778,1.20,196491.47250,181040,92171,298532
2165,11,11001,11001000,110011000000009219,0.058952,0.000052,9219,"POLYGON ((-74.11956 4.74809, -74.11954 4.74809...",0.641471,POINT (-74.12417 4.74352),...,51,14,1,1,6778,1.20,196491.47250,181040,92171,298532
2166,11,11001,11001000,110011000000009220,0.036532,0.000043,9220,"POLYGON ((-74.09222 4.73695, -74.09221 4.73695...",0.528884,POINT (-74.09257 4.73487),...,135,35,0,1,12226,2.38,362496.90030,234887,143260,388004
2167,11,11001,11001000,110011000000009221,0.033188,0.000028,9221,"POLYGON ((-74.12395 4.74975, -74.12378 4.74919...",0.349619,POINT (-74.12691 4.74612),...,51,14,1,1,6778,1.20,196491.47250,181040,92171,298532
2168,11,11001,11001000,110011000000009222,0.083100,0.000214,9222,"POLYGON ((-74.11508 4.76192, -74.11392 4.76096...",2.656149,POINT (-74.10850 4.75636),...,51,14,1,1,6778,1.20,196491.47250,181040,92171,298532

In [ ]:
sectorUrbanoWithVariablesNormalized = sectorUrbanoWithVariables.copy()
variables = sectorUrbanoWithVariables.columns[-15:].tolist()

for var in variables:
#for var in variables[-3:]:
    print(var)
#for var in ['Geographic spark']:
    fig1, ax1 = plt.subplots(dpi=50)
    sns.distplot(sectorUrbanoWithVariables[var], ax = ax1, bins=30, kde_kws={"color": "none"},);

    kernel = gaussian_kde(sectorUrbanoWithVariables[var])

    pdf_fitted = kernel.evaluate(sectorUrbanoWithVariables[var])
    X = np.array([sectorUrbanoWithVariables[var], pdf_fitted]).T
    X = X[X[:,0].argsort()]
    ax1.plot(X[:, 0], X[:, 1], label='kde', c='C3')

    ax1.set_xlim(sectorUrbanoWithVariables[var].min(), sectorUrbanoWithVariables[var].max())
    ax1.set_ylabel('Probability Density')

    
    ax1.legend()

    fig1.tight_layout()        
    fig1.savefig(var + '_dist.pdf', format='pdf')
    
    if var == 'SocioSpatial segregation':
        sectorUrbanoWithVariablesNormalized[var + '- Normalized'] = 1 - sectorUrbanoWithVariablesNormalized[var].apply(lambda x: kernel.integrate_box_1d(0, x))
    elif var == 'population':
        sectorUrbanoWithVariablesNormalized[var + '- Normalized'] = sectorUrbanoWithVariablesNormalized[var].apply(lambda x: kernel.integrate_box_1d(0, x))
    else:
        sectorUrbanoWithVariablesNormalized[var + '- Normalized'] = sectorUrbanoWithVariablesNormalized[var].apply(lambda x: kernel.integrate_box_1d(0, x))
        #sectorUrbanoWithVariablesNormalized[var + '- Normalized'] = sectorUrbanoWithVariablesNormalized[var].apply(lambda x: kernel.integrate_box_1d(float('-inf'), x))
        
    '''
    min_max_scaler = preprocessing.MinMaxScaler()
    X_train_minmax = min_max_scaler.fit_transform(sectorUrbanoWithVariablesNormalized[[var + '- Normalized']])
    sectorUrbanoWithVariablesNormalized[var + '- Normalized'] = X_train_minmax
    '''
        
    if var == 'population':
        ax1.set_xlabel('Consequence')
        
    if var == 'Geographic spark':
        ax1.set_xlabel('Threat')
        AirportsAndTerminals = list(map(str,[6303, 4523, 8527, 5624]))
        indexAirportsAndTerminals = sectorUrbanoWithVariables[sectorUrbanoWithVariables['SETU_CCDGO'].isin(AirportsAndTerminals)].index        
        for index in indexAirportsAndTerminals:
            print(index)
            #sectorUrbanoWithVariablesNormalized.at[index, 'Geographic spark- Normalized'] = 1
            sectorUrbanoWithVariablesNormalized.at[index, 'Geographic spark- Normalized'] = 0.62
            # print(sectorUrbanoWithVariablesNormalized.at[index, 'Geographic spark- Normalized'])
            
        print(sectorUrbanoWithVariablesNormalized['Geographic spark- Normalized'].max())
        
        #plotVulnerabilityMap_withDistribution(sectorUrbanoWithVariablesNormalized, var + '- Normalized')
        
    else:
        #plotVulnerabilityMap_withDistribution(sectorUrbanoWithVariablesNormalized, var + '- Normalized')